name: "create license data json"

on:
  schedule:
    - cron: "0 12 * * 6"

  workflow_dispatch:

jobs:
  generate-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Checkout SPDX Repo
        uses: actions/checkout@v3
        with:
          repository: "spdx/license-list-data"
          sparse-checkout: "json/details"
          path: "license-list-data"
  
      - name: Run python
        run: |
          python3 app.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated licenses update
