name: "create license data json"

on:
  schedule:
    - cron: "0 12 * * 6"

  workflow_dispatch:

jobs:
  generate-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get current spdx repo
        run: |
          git clone https://github.com/spdx/license-list-data
          python3 app.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated licenses update